create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'search')),
  path text not null default '/',
  search_query text,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid not null,
  created_at timestamptz not null default now(),
  constraint analytics_events_path_length check (char_length(path) <= 300),
  constraint analytics_events_query_length check (search_query is null or char_length(search_query) <= 300)
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_type_created_idx on public.analytics_events (event_type, created_at desc);
create index if not exists analytics_events_search_query_idx on public.analytics_events (search_query) where search_query is not null;

alter table public.analytics_events enable row level security;

create policy "Visitors can record analytics"
on public.analytics_events for insert
to anon, authenticated
with check (
  event_type in ('page_view', 'search')
  and char_length(path) <= 300
  and (search_query is null or char_length(search_query) <= 300)
  and (user_id is null or user_id = auth.uid())
);

create policy "Admins can read analytics"
on public.analytics_events for select
to authenticated
using (app_private.is_admin());

grant insert on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

create table if not exists public.contact_settings (
  id smallint primary key default 1 check (id = 1),
  phone text,
  email text,
  address text,
  facebook_url text,
  line_url text,
  instagram_url text,
  tiktok_url text,
  updated_at timestamptz not null default now()
);

insert into public.contact_settings (id, phone, email, address, facebook_url)
values (1, '089-123-4567', 'hello@condofinder.com', 'กรุงเทพมหานคร', 'https://www.facebook.com/profile.php?id=61590680163970')
on conflict (id) do nothing;

alter table public.contact_settings enable row level security;

create policy "Contact settings are public"
on public.contact_settings for select
to anon, authenticated
using (true);

create policy "Admins can manage contact settings"
on public.contact_settings for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

grant select on public.contact_settings to anon, authenticated;
grant insert, update, delete on public.contact_settings to authenticated;
